remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
title: cogito
logo: /assets/img/logo.png
description: A reasoning company.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
